// Auto-generated by AiWebAppBuilder — do not edit.
// Lightweight PostgREST client. Talks to a dedicated, isolated database schema.
// PostgREST query syntax: https://postgrest.org/en/stable/references/api/tables_views.html
//   db.select('todos', '?completed=eq.false&order=created_at.desc')
//   db.insert('todos', { title: 'Buy milk' })
//   db.update('todos', '?id=eq.1', { completed: true })
//   db.remove('todos', '?id=eq.1')

const BASE_URL = import.meta.env.VITE_POSTGREST_URL as string;
const SCHEMA = import.meta.env.VITE_DB_SCHEMA as string;
const ANON_TOKEN = import.meta.env.VITE_DB_ANON_TOKEN as string;

function buildHeaders(write: boolean): Record<string, string> {
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
    'Accept-Profile': SCHEMA,
  };
  if (write) headers['Content-Profile'] = SCHEMA;
  if (ANON_TOKEN) headers['Authorization'] = `Bearer ${ANON_TOKEN}`;
  return headers;
}

async function handle<T>(res: Response): Promise<T> {
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`PostgREST ${res.status}: ${text}`);
  }
  if (res.status === 204) return undefined as T;
  const text = await res.text();
  return (text ? JSON.parse(text) : undefined) as T;
}

export const db = {
  /** Read rows. `query` is an optional PostgREST query string starting with '?'. */
  async select<T = any>(table: string, query = ''): Promise<T[]> {
    const res = await fetch(`${BASE_URL}/${table}${query}`, { headers: buildHeaders(false) });
    return handle<T[]>(res);
  },
  /** Insert one row or an array of rows. Returns the inserted rows. */
  async insert<T = any>(table: string, values: unknown): Promise<T[]> {
    const res = await fetch(`${BASE_URL}/${table}`, {
      method: 'POST',
      headers: { ...buildHeaders(true), Prefer: 'return=representation' },
      body: JSON.stringify(values),
    });
    return handle<T[]>(res);
  },
  /** Update rows matched by `query`. Returns the updated rows. */
  async update<T = any>(table: string, query: string, values: unknown): Promise<T[]> {
    const res = await fetch(`${BASE_URL}/${table}${query}`, {
      method: 'PATCH',
      headers: { ...buildHeaders(true), Prefer: 'return=representation' },
      body: JSON.stringify(values),
    });
    return handle<T[]>(res);
  },
  /** Delete rows matched by `query`. */
  async remove(table: string, query: string): Promise<void> {
    const res = await fetch(`${BASE_URL}/${table}${query}`, {
      method: 'DELETE',
      headers: buildHeaders(true),
    });
    await handle<void>(res);
  },
};

export type Db = typeof db;